version: "3.3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 291119
      MYSQL_DATABASE: appetito
      MYSQL_USER: root
      MYSQL_PASSWORD: 291119
    restart: always
    networks:
      - appetito
    ports:
      - "3306:3306"
  autenticacao:
    image: bhdos/autenticacao:latest
    container_name: autenticacao-ms
    restart: always
    networks:
      - appetito
    ports:
      - "8081:8081"
  cadastro:
    image: bhdos/cadastro:latest
    container_name: cadastro-ms
    restart: always
    networks:
      - appetito
    ports:
      - "8082:8082"
  cardapio:
    image: bhdos/cardapio:latest
    container_name: cardapio-ms
    restart: always
    networks:
      - appetito
    ports:
      - "8083:8083"
  carrinho:
    image: bhdos/carrinho:latest
    container_name: carrinho-ms
    restart: always
    networks:
      - appetito
    ports:
      - "8084:8084"
  localizacao:
    image: bhdos/localizacao:latest
    container_name: localizacao-ms
    restart: always
    networks:
      - appetito
    ports:
      - "8086:8086"
  appetito-web:
    image: bhdos/apache:latest
    container_name: appetito-web
    restart: always
    networks:
      - appetito
    ports:
      - "8080:80"
networks:
  appetito:
    external: true